
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - database
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: mysql://app:app@database:3306/app?serverVersion=10.5.29-MariaDB&charset=utf8mb4
      MAILER_DSN: smtp://mailer:1025
    ports:
      - "8000:8000"
    volumes:
      - .:/app

###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
