#!/usr/bin/env python3
"""
Generates a merged code summary of the Symfony project: src/ + templates/

Creates: project_samenvatting.txt (in project root)

✅ Ondersteunt nu een WHITELIST:
- Zet hier relatieve paden in t.o.v. project_root, bv:
  "src/Controller/RapportageController.php"
  "templates/document/edit.html.twig"
- Wildcards (*) zijn toegestaan, bv:
  "src/Report/*.php"
- Als WHITELIST leeg is → oude gedrag (alles uit src/templates met juiste extensies)
"""

import os
import fnmatch

# Files we care about
EXTENSIONS = (".php", ".twig", ".yaml", ".yml", ".json", ".js", ".css", ".scss", ".ts", ".md")

# ---- WHITELIST: alleen deze bestanden komen in de samenvatting ----
# Gebruik relatieve paden t.o.v. project_root.
WHITELIST = [
    "public/js/effectsSettings.js",
    "src/Controller/DocumentController.php",
#     "src/Controller/EffectSettingsController.php",
#     "src/Entity/DocumentTrack.php",
#     "src/Entity/DocumentTrackEffect.php",
#     "src/Entity/EffectSettings.php",
    "src/Entity/InstrumentPart.php",
#     "src/Form/DocumentFormType.php",
#     "src/Form/DocumentTrackEffectType.php,"
#     "src/Form/DocumentTrackType.php",
#     "src/Form/EffectSettingsType.php",
    "src/Form/InstrumentPartType.php",
#     "src/Repository/EffectSettingsKeyValueRepository.php",
#     "src/Repository/EffectSettingsRepository.php",
    "src/Service/TrackEffectParamChoicesBuilder.php",
#     "templates/_partials/ui_styles.html.twig",
    "templates/Document/_track_card.html.twig",
    "templates/Document/edit.html.twig"
#     "templates/Effect/edit.html.twig",
#     "templates/Effect/index.html.twig"
]
# ------------------------------------------------------------------


def collect_files(base_path, subfolders):
    files = []
    for folder in subfolders:
        full = os.path.join(base_path, folder)
        if not os.path.isdir(full):
            continue
        for root, _, filenames in os.walk(full):
            for f in filenames:
                if f.lower().endswith(EXTENSIONS):
                    files.append(os.path.join(root, f))
    return files


def apply_whitelist(all_files, project_root):
    """Filter all_files op basis van WHITELIST. Support voor * wildcards."""
    if not WHITELIST:
        return all_files  # oude gedrag

    whitelist_norm = [w.replace("\\", "/").strip() for w in WHITELIST if w.strip()]
    filtered = []

    for path in all_files:
        rel = os.path.relpath(path, project_root).replace("\\", "/")
        if any(fnmatch.fnmatch(rel, pattern) for pattern in whitelist_norm):
            filtered.append(path)

    return filtered


def main():
    # go one directory up
    project_root = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))

    targets = ["src", "templates"]
    all_files = collect_files(project_root, targets)
    all_files.sort()

    included_files = apply_whitelist(all_files, project_root)

    output_file = os.path.join(project_root, "project_samenvatting.txt")

    with open(output_file, "w", encoding="utf-8") as out:
        out.write("### Project Code Summary\n")
        out.write("### Auto-generated by PY/samenvatting.py\n\n")

        if WHITELIST:
            out.write("### WHITELIST actief — alleen geselecteerde bestanden\n")
            for w in WHITELIST:
                out.write(f"- {w}\n")
            out.write("\n")

        if not included_files:
            out.write("[Geen bestanden gevonden die matchen met WHITELIST]\n")

        for path in included_files:
            relative = os.path.relpath(path, project_root).replace("\\", "/")

            out.write(f"\n\n---  FILE: {relative}  " + "-" * 60 + "\n\n")

            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    out.write(f.read())
            except Exception as e:
                out.write(f"[Error reading file: {e}]")

    print(f"✅ Samenvatting gemaakt: {output_file}")
    if WHITELIST:
        print(f"📌 Aantal bestanden in whitelist-output: {len(included_files)}")


if __name__ == "__main__":
    main()
