#!/usr/bin/env python3
"""
Generates a merged code summary of the Symfony project: src/ + templates/

Creates: project_samenvatting.txt (in project root)
"""

import os

# Files we care about
EXTENSIONS = (".php", ".twig", ".yaml", ".yml", ".json", ".js", ".css", ".scss", ".ts", ".md")


def collect_files(base_path, subfolders):
    files = []
    for folder in subfolders:
        full = os.path.join(base_path, folder)
        for root, _, filenames in os.walk(full):
            for f in filenames:
                if f.lower().endswith(EXTENSIONS):
                    files.append(os.path.join(root, f))
    return files


def main():
    # go one directory up
    project_root = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))

    targets = ["src", "templates"]
    all_files = collect_files(project_root, targets)
    all_files.sort()

    output_file = os.path.join(project_root, "project_samenvatting.txt")

    with open(output_file, "w", encoding="utf-8") as out:
        out.write("### Project Code Summary\n")
        out.write("### Auto-generated by PY/samenvatting.py\n\n")

        for path in all_files:
            relative = os.path.relpath(path, project_root)

            out.write(f"\n\n---  FILE: {relative}  " + "-" * 60 + "\n\n")

            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    out.write(f.read())
            except Exception as e:
                out.write(f"[Error reading file: {e}]")

    print(f"✅ Samenvatting gemaakt: {output_file}")


if __name__ == "__main__":
    main()
